### PR TITLE
Fix3

### PR DESCRIPTION
**Pull request by PhilippeCharlot22**

### CODE REVIEW

**Comment by PhilippeCharlot22** [comment]
use if not val in test_aai_service_instance.py

**Comment by devfest-bugbust** [comment]
Could you put proper commit message and description ? probably something like

commit message:  "use if not val in test_aai_service_instance.py"

 description: Following https://www.python.org/dev/peps/pep-0008/#programming-recommendations#:~:text=if%20not%20seq recommendation.

**Comment by PhilippeCharlot22** [comment]
use if not val in test_aai_service_instance.py

**Comment by devfest-bugbust** [comment]
Since PR needs to be rebase and merged to be able to attribute points we were more expecting this "use if not val in test_aai_service_instance.py" into the commit message  instead of fix3 .

Accepting for now :)

**Pull request merged**
